variables:
  PROJECT_NAME: "PaketGlobal"
before_script:
  - nuget restore
  - 'echo Start-BitsTransfer "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe" >> download_nuget.ps1'
  - powershell -ExecutionPolicy Unrestricted "& "".\download_nuget.ps1""" 
  - del download_nuget.ps1
  - nuget.exe restore
  - del nuget.exe
stages:
  - build
job:
  stage: build
  script:
    - cd Droid
    - msbuild /t:SignAndroidPackage /t:restore /p:Configuration=Release /p:AndroidEnableMultiDex=true
  artifacts:
    expire_in: 1 week
    paths:
      - 'Droid/bin/Release/*.apk'
  tags:
      - Xamarin
  only:
      - tags
