variables:
  PROJECT_NAME: "PaketGlobal"
stages:
  - build
job:
  stage: build
  before_script:
  script:
  - echo "Release build..."
  - set PATH=%PATH%;%ANDROID_HOME%\tools\bin;%ANDROID_HOME%\build-tools\25.0.3
  #- 'msbuild /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /p:Configuration=Release /p:Platform="Any CPU" /p:AndroidSdkDirectory=%ANDROID_HOME% /p:androidSdkPath=%ANDROID_HOME% /t:rebuild /verbosity:quiet "%PROJECT_NAME%.sln"'
  - 'MSBuild "/t:SignAndroidPackage" "/p:Configuration=Debug" "Droid\PaketGlobal.Droid.csproj"'
  #after_script:
  #- 'rd "%CI_PROJECT_DIR%"'

  artifacts:
    expire_in: 1 week
    paths:
    - 'Droid/bin/Debug/*.apk'
  tags:
    - Android
    - Xamarin
    - Windows
  only:
    - tags